-- INSERT INTO PROJECT(projectid, name, description) VALUES(1, 'DESARROLLO DE APLICACIONES MOVILES', 'Proyecto 1');
-- INSERT INTO PROJECT(projectid, name, description) VALUES(2, 'PARAMETRIZACIONES DE PRODUCTOSS', 'Proyecto 2');
-- INSERT INTO TASK(taskid, title,description, status, projectid) VALUES(1, 'Task1','description anothe of the one','POR HACER',1);
-- INSERT INTO TASK(taskid, title,description, status, projectid) VALUES(2, 'Task2','description anothe of the one','POR HACER',1);
-- INSERT INTO TASK(taskid, title,description, status, projectid) VALUES(3, 'Task1','description anothe of the one','COMPLETADO',2);